name: ng_modular_admin_demo
description: Demo for ng_modular_admin
authors:
- Mark E. Haase <mehaase@gmail.com>

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: ^4.0.0
  angular_forms: ^1.0.0
  angular_router: ^1.0.2
  ng_fontawesome: ^4.7.0
  ng_modular_admin: any

dependency_overrides:
  ng_modular_admin:
    path: ..

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- angular:
    entry_points: web/main.dart
- dart_to_js_script_rewriter

web:
  compiler:
    debug: dartdevc
