name: ng_modular_admin
version: 1.0.1
description: >
  Modular Admin for Angular Dart is a Boostrap theme for building web
  applications.
homepage: https://github.com/hyperiongray/ng_modular_admin
authors:
- Mark E. Haase <mehaase@gmail.com>
environment:
  sdk: '>=2.2.0 <3.0.0'
dependencies:
  angular: '^5.2.0'
  angular_forms: ^2.1.1
  angular_router: ^2.0.0-alpha+21
  ng_fontawesome: '^5.7.2'
dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  sass_builder: ^2.1.2
